version: "3.8"

services:
  ntfy:
    # https://hub.docker.com/r/binwiederhier/ntfy
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=${TIMEZONE}
    user: 0:0
    volumes:
      - ./ntfy_config/server.yml:/etc/ntfy/server.yml
      - ntfy_cache:/var/cache/ntfy
    ports:
      - "8080:80"
    networks:
      - n8n_ntfy_net
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=Zinger
      - N8N_BASIC_AUTH_PASSWORD=Bazinger
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678
      - GENERIC_TIMEZONE=Europe/Berlin
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  ntfy_cache:
  n8n_data:

networks:
  n8n_ntfy_net:
