version: '3'

services:
  ntfy:
    # https://hub.docker.com/r/binwiederhier/ntfy
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=${TIMEZONE}
    user: 0:0
    volumes:
      - ./ntfy_config/server.yml:/etc/ntfy/server.yml
      - ntfy_cache:/var/cache/ntfy
    ports:
      - "8080:80"
    networks:
      - n8n_ntfy_net
    restart: unless-stopped

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n_ntfy_net
    restart: unless-stopped

volumes:
  ntfy_cache:
  n8n_data:

networks:
  n8n_ntfy_net: